### ISSUE TITLE
Installation of TTWKPieChart

### ISSUE THREAD

**Issue by hyerra** [TouchTribe/TTWKPieChart#2]
So, I am really having trouble trying to install the TTWKPieChart Framework into my watchOS app. I have tried adding the following code in my Podfile:

```
# Uncomment this line to define a global platform for your project
# platform :iOS, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MyApp' do

end

target 'MyApp WatchKit App' do

end

target 'MyApp WatchKit Extension' do
    platform :watchos, '2.0'
    pod 'TTWKPieChart'
end
```

Then, when I run such code I get the error that TTWKPieChart doesn't support watchOS. So then, I move the pod 'TTWKPieChart' code into the 'MyApp' section of the Podfile like so:

```
# Uncomment this line to define a global platform for your project
# platform :iOS, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MyApp' do
     pod 'TTWKPieChart'
end

target 'MyApp WatchKit App' do

end

target 'MyApp WatchKit Extension' do
    platform :watchos, '2.0'
end
```

The only issue this time is that I can't even put any of the TTWKPieChart code into my WatchKit extension.

**Comment by aleh** [comment]
Thanks for raising the issue! 

The first variant you've tried should have worked, however the library was created before cocoapods supported 'watchos' platform, so the platform was not stated in the podspec. I've updated it now, see pull request https://github.com/TouchTribe/TTWKPieChart/pull/3.

Before the pull request is approved in you can refer to my fork in your Podfile: https://github.com/aleh/TTWKPieChart

**Comment by hyerra** [comment]
Thanks :). I was really confused as to why it wasn't working. I'll use your fork for now.
